
Showing logs for build [32mtrietlu-flask-jx-sample-pr-17-s-qh4tw-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-jghdr[0m
{"level":"warn","ts":1581971687.2596757,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581971687.2599518,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mtrietlu-flask-jx-sample-pr-17-s-qh4tw-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-9b6z2[0m
{"level":"warn","ts":1581971687.648121,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581971687.6492074,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mtrietlu-flask-jx-sample-pr-17-s-qh4tw-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mtrietlu-flask-jx-sample-pr-17-s-qh4tw-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-trietlu-flask-jx-sample-pr-17-s-qh4tw-s745p[0m
{"level":"warn","ts":1581971693.7386081,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581971694.0243502,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/*******/flask-**-sample.git @ master in path /workspace/source"}

Showing logs for build [32mtrietlu-flask-jx-sample-pr-17-s-qh4tw-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:f115aceaea880a427ba0da34da41f6c6a8282168,17:1e9d986c8dfc6a3e33d7225333c1d35a1369b3b8
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 1e9d986c8dfc6a3e33d7225333c1d35a1369b3b8: f115aceaea880a427ba0da34da41f6c6a8282168:
DEBUG: ran git fetch --unshallow origin 1e9d986c8dfc6a3e33d7225333c1d35a1369b3b8: f115aceaea880a427ba0da34da41f6c6a8282168: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git reset --hard f115aceaea880a427ba0da34da41f6c6a8282168
DEBUG: ran git reset --hard f115aceaea880a427ba0da34da41f6c6a8282168 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 1e9d986c8dfc6a3e33d7225333c1d35a1369b3b8
DEBUG: ran git merge 1e9d986c8dfc6a3e33d7225333c1d35a1369b3b8 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e f115aceaea880a427ba0da34da41f6c6a8282168..HEAD
Merged SHA 11e1f699b2747afc7ece8263df8d870bf40f7601 with commit message 'Merge commit '1e9d986c8dfc6a3e33d7225333c1d35a1369b3b8'' into base branch master
Merged SHA 1e9d986c8dfc6a3e33d7225333c1d35a1369b3b8 with commit message 'Update flask_app.py' into base branch master
Merged SHA 325a818efd06f9cefec2a61439321b251145fcf2 with commit message 'Update flask_app.py' into base branch master
Merged SHA 8439cb5af720717d8f8c9f926d20dab1ec37b054 with commit message 'Update flask_app.py' into base branch master

Showing logs for build [32mtrietlu-flask-jx-sample-pr-17-s-qh4tw-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-code-scan[0m
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting python-taint
  Downloading https://files.pythonhosted.org/packages/5c/79/5b70d3299cb7dea63e2b015651c5c7507d723911ff2837e104ebd7079491/python_taint-0.42-py3-none-any.whl (52kB)
Installing collected packages: python-taint
Successfully installed python-taint-0.42
1 vulnerability found:
Vulnerability 1:
File: flask_app.py
 > User input at line 17, source "request.args.get(":
	 ~call_1 = ret_request.args.get('param', 'not set')
Reassigned in:
	File: flask_app.py
	 > Line 17: param = ~call_1
File: flask_app.py
 > reaches line 22, sink "replace(":
	~call_5 = ret_html.replace('{{ param }}', param)

[31m
Pipeline failed on stage 'from-build-pack' : container 'step-build-code-scan'. The execution of the pipeline has stopped.[0m
